[package]
name = "left-todo-action"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = "symbols"