name: Build and Publish Docker Image

# TODO Define workflow for building and publishing your Docker image
on:  
   workflow_dispatch:
   push:
      branches:
         - main

jobs:
   build-and-push-image:
      name: Build and push image
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ghcr.io/${{ github.repository }}